### ISSUE TITLE
ClassNotFoundException: ma.glasnost.orika.impl.GeneratedMapperBase on remote jetty server

### ISSUE THREAD

**Issue by idelpivnitskiy** [orika-mapper/orika#62]
I have a Spring Boot application which uses websockets and Orika. I'm using war packaging (instead of jar) and `spring-boot-maven-plugin` generates 2 versions by default:
* myproject.war - executable war package which consist jetty server, I'm able to run it with `java -jar myproject.war`;
* myproject.war.original - war package without embedded jetty server which I use to deploy to remote jetty server.  

First version of war works fine! And I haven't got any problems with it. But on remote jetty server I have an exception in my websocket controller:
```
ma.glasnost.orika.MappingException: ma.glasnost.orika.impl.generator.CompilerStrategy$SourceCodeGenerationException: Error compiling ma.glasnost.orika.generated.Orika_MessageEntity_MessageRequestDto_Mapper4074936221257$2
	at ma.glasnost.orika.impl.generator.MapperGenerator.build(MapperGenerator.java:105)
	at ma.glasnost.orika.impl.DefaultMapperFactory.buildMapper(DefaultMapperFactory.java:1360)
	at ma.glasnost.orika.impl.DefaultMapperFactory.lookupMapper(DefaultMapperFactory.java:757)
	at ma.glasnost.orika.impl.DefaultMapperFactory.lookupMapper(DefaultMapperFactory.java:707)
	at ma.glasnost.orika.impl.MapperFacadeImpl.resolveMapper(MapperFacadeImpl.java:584)
	at ma.glasnost.orika.impl.MapperFacadeImpl.resolveMappingStrategy(MapperFacadeImpl.java:216)
	at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:734)
	at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:714)
	at myproject.controller.websocket.chat.ChatController.sending(ChatController.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:185)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:104)
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMatch(AbstractMethodMessageHandler.java:447)
	at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:443)
	at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:82)
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessageInternal(AbstractMethodMessageHandler.java:408)
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessage(AbstractMethodMessageHandler.java:346)
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:135)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: ma.glasnost.orika.impl.generator.CompilerStrategy$SourceCodeGenerationException: Error compiling ma.glasnost.orika.generated.Orika_MessageEntity_MessageRequestDto_Mapper4074936221257$2
	at ma.glasnost.orika.impl.generator.JavassistCompilerStrategy.compileClass(JavassistCompilerStrategy.java:266)
	at ma.glasnost.orika.impl.generator.SourceCodeContext.compileClass(SourceCodeContext.java:249)
	at ma.glasnost.orika.impl.generator.SourceCodeContext.getInstance(SourceCodeContext.java:266)
	at ma.glasnost.orika.impl.generator.MapperGenerator.build(MapperGenerator.java:75)
	... 23 common frames omitted
Caused by: javassist.CannotCompileException: by java.lang.NoClassDefFoundError: ma/glasnost/orika/impl/GeneratedMapperBase
	at javassist.ClassPool.toClass(ClassPool.java:1120)
	at javassist.ClassPool.toClass(ClassPool.java:1063)
	at javassist.ClassPool.toClass(ClassPool.java:1021)
	at javassist.CtClass.toClass(CtClass.java:1259)
	at ma.glasnost.orika.impl.generator.JavassistCompilerStrategy.compileClass(JavassistCompilerStrategy.java:259)
	... 26 common frames omitted
Caused by: java.lang.NoClassDefFoundError: ma/glasnost/orika/impl/GeneratedMapperBase
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at javassist.ClassPool.toClass2(ClassPool.java:1133)
	at javassist.ClassPool.toClass(ClassPool.java:1114)
	... 30 common frames omitted
Caused by: java.lang.ClassNotFoundException: ma.glasnost.orika.impl.GeneratedMapperBase
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 common frames omitted
```
The exception is caused in a class:
```java
@Controller
public class ChatController {

    @Autowired
    private MapperFacade mapper;

    ...

    @MessageMapping("/chat/{roomId}")
    public void sending(MessageRequestDto messageRequestDto, @DestinationVariable("roomId") long roomId, Authentication authentication) throws Exception {
        MessageEntity messageEntity = mapper.map(messageRequestDto, MessageEntity.class);
        ...
    }
```
Another strange, that it works fine in all my `@RestController`s, for example:
```java
@RestController
@RequestMapping(value = "/api/rooms",
        consumes = MediaType.APPLICATION_JSON_VALUE,
        produces = MediaType.APPLICATION_JSON_VALUE)
public class RoomController {

    @Autowired
    private IRoomService roomService;

    @Autowired
    private IMessageService messageService;

    @Autowired
    private MapperFacade mapper;

    @RequestMapping(value = "/{roomId}/messages", method = RequestMethod.GET)
    public List<MessageResponseDto> getRoomMessages(@PathVariable long roomId,
            @RequestParam(value = "offset", defaultValue = "0") int offset,
            @RequestParam(value = "limit", defaultValue = Constants.LIMIT) int limit) {
        ...
        List<MessageEntity> messages = messageService.findMessagesByRoomId(roomId, offset, limit);
        return mapper.mapAsList(messages, MessageResponseDto.class);
    }
```
`MessageResponseDto extends MessageRequestDto`

My Orika config:
```java
@Component
public class MapperFacadeFactory implements FactoryBean<MapperFacade> {

    @Override
    public MapperFacade getObject() throws Exception {
        final MapperFactory mapperFactory = new DefaultMapperFactory.Builder().build();
        mapperFactory.getConverterFactory().registerConverter(new LocalDateTimeConverterToLocalDateTimeConverter());
        mapperFactory.classMap(MessageEntity.class, MessageResponseDto.class)
                     .fieldAToB("user.fullName", "userName")
                     .byDefault()
                     .register();

        return mapperFactory.getMapperFacade();
    }

    @Override
    public Class<?> getObjectType() {
        return MapperFacade.class;
    }

    @Override
    public boolean isSingleton() {
        return true;
    }
}
```
Remote and embedded jetty servers have the same version number: jetty-9.2.9.v20150224
Java version:
```
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)
```
Orika version: 1.4.5
Spring Boot version: 1.2.3-RELEASE

**Comment by idelpivnitskiy** [comment]
Another strange fact:
For chat implementation I'm using Stomp and SockJS, like this: https://spring.io/guides/gs/messaging-stomp-websocket/
This implementation supports different protocols: https://github.com/sockjs/sockjs-client#supported-transports-by-name
And the excpection caused only when it works through `websocket` protocol. If I will change the protocol to `xhr-streaming` in my frontend implementation, it will works fine!

**Comment by elaatifi** [comment]
Sorry for the late reply
Did you have a unit test (or small project) to reproduce the error ?

**Comment by asegarra** [comment]
There seems to be a problem with 1.4.5 using Java 8 and appears to be fixed in 1.4.6.

**Comment by idelpivnitskiy** [comment]
@elaatifi I'll prepare a small project next month, I haven't got enough time now.
Thanks!

**Comment by newcgen** [comment]
Hello!

I am using Orika in Java EE 6 environment.
I get following exception.
```
Caused by: java.lang.NoClassDefFoundError: name/of/my/Class
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2483)
	at java.lang.Class.getConstructor0(Class.java:2793)
	at java.lang.Class.newInstance(Class.java:345)
	at ma.glasnost.orika.impl.generator.SourceCodeContext.getInstance(SourceCodeContext.java:266)
	at ma.glasnost.orika.impl.generator.MapperGenerator.build(MapperGenerator.java:75)
	at ma.glasnost.orika.impl.DefaultMapperFactory.buildMapper(DefaultMapperFactory.java:1372)
	at ma.glasnost.orika.impl.DefaultMapperFactory.build(DefaultMapperFactory.java:1199)
	at ma.glasnost.orika.impl.DefaultMapperFactory.getMapperFacade(DefaultMapperFactory.java:859)
```
A similar problem exists and Dozer.
But Dozer allows to replace the default ClassLoader with a custom one.
This workaround solves the problem.

**Comment by rickla** [comment]
I got these also in a grails environment when I updated to 1.4.6, so had to revert back.

**Comment by Jtalk** [comment]
This is because JavassistCompilerStrategy uses it's own ClassLoader to load mapping bean classes. Deployment artifacts (WAR, EJB-JAR) and deployment dependencies (/lib/*.jar)  are being loaded by different class loaders in some application servers (e.g. in Glassfish). Deployment loader is usually a child of the libraries' one, so JavassistCompilerStrategy cannot access you deployment classes from the parent CL. 

The simple workaround is to subclass JavassistCompilerStrategy in your deployment so it's class is loaded by deployment CL. Your overridden class should then be manually applied to the Orika MapperFactory (new DefaultMapperFactory.Builder().compilerStrategy(new YourSubclass()).build() should do the trick). 

The actual fix would be to provide JavassistCompilerStrategy with a dependency injection capability allowing it to use custom ClassLoader and ProtectionDomain for mapping classes.

**Comment by dickerpulli** [comment]
@idelpivnitskiy Have you solved the problem by now?

**Comment by idelpivnitskiy** [comment]
@dickerpulli no, I decided to use runnable version with embedded Jetty instead of separate Jetty container
